# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51205d41349616d0ca47c9ed5d0c8ebdb2557e2ed668485973153b593d4f3443892d5689f16cee2d3e04133b17701cf634a4c3540f4a55c344efa49edd3344ab

test:
  secret_key_base: 7d5a95ed1a216118beacd66fb4598fda9a35d7b7fc5b37d6b801027e2a195cc1d012e680efb160edeb7ebe1536970937bbba3cac043750cee4712f7930a81774

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
